#!/bin/sh
sqlite3 ../../AdventureWorks.db << EOF
.mode html
.output adventureworks_docs_v2.html
.headers on
.print <html>
.print <h1>List of Database tables</h1>
.print ------------
.print <section>
.tables
.print </section>
.print <h2>DimCurrency</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimCurrency');
.print </table>
.print <h2>DimProductCategory</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimProductCategory');
.print </table>
.print <h2>FactInternetSalesReason</h2>
.print </hr>
.print <table>
PRAGMA table_info('FactInternetSales');
.print </table>
.print <h2>DimCustomer</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimCustomer');
.print </table>
.print <h2>DimProductSubcategory</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimProductSubCategory');
.print </table>
.print <h2>FactResellerSales</h2>
.print </hr>
.print <table>
PRAGMA table_info('FactResellerSales');
.print </table>
.print <h2>DimDate</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimDate');
.print </table>
.print <h2>DimPromotion</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimPromotion');
.print </table>
.print <h2>FactSurveyResponse</h2>
.print </hr>
.print <table>
PRAGMA table_info('FactSurveyResponse');
.print </table>
.print <h2>DimDepartmentGroup</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimDepartmentGroup');
.print </table>
.print <h2>DimReseller</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimReseller');
.print </table>
.print <h2>DimEmployee</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimEmployee');
.print </table>
.print <h2>DimSalesReason</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimSalesReason');
.print </table>
.print <h2>DimGeography</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimGeography');
.print </table>
.print <h2>DimSalesTerritory</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimSalesTerritory');
.print </table>
.print <h2>DimOrganization</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimOrganization');
.print </table>
.print <h2>FactCurrencyRate</h2>
.print </hr>
.print <table>
PRAGMA table_info('FactCurrencyRate');
.print </table>
.print <h2>DimProduct</h2>
.print </hr>
.print <table>
PRAGMA table_info('DimProduct');
.print </table>
.print <h2>FactInternetSales</h2>
.print </hr>
.print <table>
PRAGMA table_info('FactInternetSales');
.print </table>
.print </html>
.quit
EOF